In [1]:
from ultralytics import YOLO
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

In [2]:
model = YOLO("yolov8m.pt")

C:\Users\soham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ultralytics\nn\tasks.py:341: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues

In [3]:
import torch.multiprocessing as mp
mp.set_start_method('spawn', force=True)

In [7]:
model.to('cuda')
model.train(data="ALPERS/data.yaml", epochs=1, batch = 8, workers=0)

yolo\engine\trainer: task=detect, mode=train, model=yolov8m.yaml, data=ALPERS/data.yaml, epochs=1, patience=50, batch=8, imgsz=640, save=True, cache=False, device=None, workers=0, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=False, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=True, dnn=False, plots=False, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, retina_masks=False, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_moment

In [11]:
infer = YOLO("runs/detect/train2/weights/best.pt")

C:\Users\soham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ultralytics\nn\tasks.py:341: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues

In [12]:
infer.predict("ALPERS/test/images", save = True)

Ultralytics YOLOv8.0.3  Python-3.11.9 torch-2.4.1+cu118 CUDA:0 (NVIDIA GeForce RTX 4050 Laptop GPU, 6140MiB)
Fusing layers... 
Model summary: 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs
image 1/48 D:\all_files\Work\focused\Clg\new_work\ML\ALPERS\test\images\00000005_jpg.rf.987841732b1c12cf778ad437cde8d3dd.jpg: 640x640 2 plates, 31.4ms
image 2/48 D:\all_files\Work\focused\Clg\new_work\ML\ALPERS\test\images\00000035_jpg.rf.f1864b07d71add5b957f01698eb350e6.jpg: 640x640 1 plate, 32.0ms
image 3/48 D:\all_files\Work\focused\Clg\new_work\ML\ALPERS\test\images\00000045_jpg.rf.552cc11f4e35579a8f41cb8ac7447208.jpg: 640x640 2 plates, 30.7ms
image 4/48 D:\all_files\Work\focused\Clg\new_work\ML\ALPERS\test\images\00000104_jpg.rf.2c4f7290dd01e1ab6915b5f11c56e901.jpg: 640x640 2 plates, 31.8ms
image 5/48 D:\all_files\Work\focused\Clg\new_work\ML\ALPERS\test\images\00000139_jpg.rf.baf47ff9c2601c0e2d94c32c03943728.jpg: 640x640 3 plates, 14.9ms
image 6/48 D:\all_files\Work\focused\Clg\new_w

[tensor([[130.00000, 278.00000, 511.00000, 466.00000,   0.95459,   0.00000],
         [ 58.00000, 176.00000, 575.00000, 259.00000,   0.91406,   0.00000]], device='cuda:0'),
 tensor([[187.00000, 266.00000, 423.00000, 408.00000,   0.84863,   0.00000]], device='cuda:0'),
 tensor([[100.00000, 273.00000, 538.00000, 536.00000,   0.94043,   0.00000],
         [ 17.00000, 129.00000, 614.00000, 247.00000,   0.85742,   0.00000]], device='cuda:0'),
 tensor([[ 98.00000,  89.00000, 577.00000, 231.00000,   0.93555,   0.00000],
         [148.00000, 254.00000, 500.00000, 588.00000,   0.92236,   0.00000]], device='cuda:0'),
 tensor([[106.00000, 269.00000, 539.00000, 615.00000,   0.93457,   0.00000],
         [ 30.00000,  79.00000, 620.00000, 231.00000,   0.79443,   0.00000],
         [102.00000, 264.00000, 235.00000, 615.00000,   0.68750,   0.00000]], device='cuda:0'),
 tensor([[113.00000, 276.00000, 524.00000, 482.00000,   0.93994,   0.00000],
         [ 27.00000, 166.00000, 608.00000, 262.00000,   0.